apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stalwart
resources:
  - namespace.yaml
  - repository.yaml
  - certificate.yaml
  - recovery-admin-secret.yaml
  - release.yaml
secretGenerator:
  - name: stalwart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
