# cert-manager-webhook-ovh Values
# Replicas
replicaCount: 1
# Resource settings
resources:
    requests:
        cpu: 10m
        memory: 32Mi
    limits:
        cpu: 100m
        memory: 128Mi
sops:
    lastmodified: "2026-07-09T22:12:21Z"
    mac: ENC[AES256_GCM,data:WC6VezA/Ks5BxalXRBWIGwBt9k0pTUY8etW33aBT7PrWFqQVC6XlHs4z6KHU0ka6uMc1JSaprw5QdvrOr1kKQUqgIJn9v/qELT8alOd9qzJkyLImEyH7NdI8N5hzgeEpFT1O0B+tFJ4IVxcQAQusr30dZo1AUE8JV2EUEE0OaJI=,iv:KuzSPwYaYm6cf0FBRKRXlK6m9lNVKtdhxnQryGRGtlw=,tag:ES71sI0rUctXhHXtFJ0nQg==,type:str]
    pgp:
        - created_at: "2026-07-09T22:12:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//bXWkHjGoQhrI1yEwJSAi3j68wFOdO/GdGhX3ADZw8njM
            b0fQdk+3WI7IDXV9l+Ii2PHP2gMZs8S+ejKXdhMrd28xefxwuJ5dtuOjhxdAPA7M
            2jc8gitEpQW/TKHlyDfgaWIqLeJ/O/kuhYRfl0hQ3gYMjoHwZl/rrYlbSTT6jRLH
            pbjILIIo3BAXQQJgthd+y7YL6G4QjVB96wgmPEoD7FBjarNZPlPpG7EzcPj6WB9a
            rs3o7uudhjWZIKrJm0qbABxnkd1IPwwNvc/bvVMeXFPP3w8ZAD6spvBMPzrfGfSb
            45SWw4lhwR57hrsK/cGVlQSwkJxhopndvk/apb2oE4q6dUbHSX21bRmjR+HO6E5A
            eZgb8mcWFLgWmjrrAgZWvOSABV18s2d3EF6Vi8gAn8iLr6FjJcb3cfptbNOp26bT
            2nGW5Ws3UZQEzcDveUJACJRhz7pir0Cn8kZ2xsdYX0KThJ62q9b13X05nisnPVVy
            Q/NFPDTOBWIjh/TxaaOe2CXJxnKHSnxmLbfIFFOimc/P8HyBwFRT2L7MRKosTqI/
            9zKyppxoi0Cu0KPG/0hF6FN7sQ32oPQwuzuaxhuIYIzyXoohrZ1QvlV7ZsFneHcl
            0izl8HdM6+1CBy4Oiok6dWr1tGKuQVucWUUUDyvUg4h19LLNMT5eJe0/w1wsis/S
            XgEE7DsaGavusuoEfkfx2y11mMHl6qnMNQgcRBLfq2vEpPgA4U3FB0lNrgMc5oHe
            PdiBa789boiYQ13+XJIfgDkUrF9Isznkak7PYiCRgpp3LhlKVSqLasTdSKYm93g=
            =0cB0
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
