services:
  syncthing-valentin:
    image: syncthing/syncthing:2.0
    container_name: syncthing-valentin
    hostname: syncthing-valentin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config:/var/syncthing/config
      - valentin_documents:/valentin/Documents
      - valentin_photos:/valentin/Photos
    ports:
      - target: 22000
        published: 22000
        mode: host
      - target: 21027
        published: 21027
        mode: host
      - 8384
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-valentin.rule=Host(`syncthing-valentin.lan`)"
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 10m
      timeout: 10s
      retries: 5

volumes:
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/syncthing-valentin/config'
  valentin_documents:
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.lan'
      device: ':/mnt/main_storage/valentin/Documents'
  valentin_photos:
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.lan'
      device: ':/mnt/main_storage/valentin/Photos'
