apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "local-pool"
spec:
  blocks:
  - cidr: "10.2.1.210/32"
  - cidr: "10.2.1.211/32"
  - cidr: "10.2.1.212/32"
  - cidr: "10.2.1.213/32"
