apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "local-pool"
spec:
  blocks:
  - cidr: "10.2.2.3/32"
  - cidr: "10.2.2.4/32"
  - cidr: "10.2.2.5/32"
  - cidr: "10.2.2.6/32"
