apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: csi-driver-nfs
      chart: csi-driver-nfs
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: csi-driver-nfs-values
