storageClass:
    create: true
    name: nfs-csi
    annotations:
        storageclass.kubernetes.io/is-default-class: "false"
    parameters:
        server: truenas.lan
        share: /mnt/fast_app_data/kube/
        subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
    reclaimPolicy: Delete
    mountOptions:
        - noatime
        - nfsvers=4.1
driver:
    mountPermissions: 0
feature:
    enableFSGroupPolicy: true
sops:
    lastmodified: "2026-08-26T19:29:16Z"
    mac: ENC[AES256_GCM,data:NapXtPezjbRh2RVcv8Pi5/jS+TxCsPEVCXhWBLIuvfC4wWuwKelqjX1BjH4B0zTlEVzPzXKkeLyT5Kz0Jh68hwltSPCzF+32BqzpxpP1PD/ErvLvjtagRwnoV7KVN0MuR7RyNusFQUBDVXll9dHp5R7eUIcpe0S2qkVWiqnbx5c=,iv:ynnKQThC7PLua9tNTJLRp1b+V9yp6yUtKtd8fgvkol0=,tag:3r/XZYwK+G4sv+GAHQ2OCQ==,type:str]
    pgp:
        - created_at: "2026-08-26T19:29:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiARAAoaqSEhJGt0xxhujiIxgrHc0psSFXl9USxXJWYsxFAB5e
            ypcxbemrGtf4cTQn8Ol/pEF/hd8q7NlUnfggBYua9jX5O2jTUYe6v/l67Jxvux/Y
            X3nt9BmsizFEpHsm4QicsNfqnxJMEWILKA2A+35SBIfRIgqcEP03JrJKkOIsbAkD
            taNxfHhJEgJlctqnGgIK8KSXQQhYohZiOLukTpfwY8nys+O4dfz7lPu9jlF3GZHM
            2BZgbEb3+dNq4MsJIysy8ECUCZVuMuhxYHgogcXmm7iZXDoc+ala3CVjGwi/KBVx
            aD4UBG06kacMaiM9ddpelmTvkD4/GHl1FFCoiIkVelmNMVjD5aecn4xl6r15CC4J
            IQRO2Jc72sLPAjQsiq9El6K0hFoWj9v4L7xLDbE/1KozjVK8eUtKT5r5p5t5JOvq
            wvD2TfjDwxdosJ/hkCj6FwvGZxvUUHAyXIN82Q8nMMldjyqtww0JbSOLEz8sZFds
            AqbTz95kNYZGSoJRa6OYOdXYQk0wG89sqBm5taFm6V9N0hsgv6y7Od21wEgHKxKX
            GMR/K/mlZ8lr30Tb3KhCgPQ5JpyDKBIvGuAJLnlVE5//wkj7Qd+xXAiZX7qhNFBq
            ZNy7FKLSC83l5hFKFyFbELe7VPB7YaBGy2312uZue+WQgchndFgRataROaFcz43S
            XgHovdD6j4T/AEd7N/l+pd6Za8Xejc25+37F3i2Mstbme2Nh8pEqkogRk0zgpJKS
            /Y/FtQl8+lpJAwiOAbghZYnflvK9bLnTa4cR5MXb737G4MjMg29sPP7sEJGdhpQ=
            =Xr/t
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
