storageClass:
    create: true
    name: nfs-csi
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    parameters:
        server: truenas.lan
        share: /mnt/fast_app_data/kube/
        subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
    reclaimPolicy: Delete
    mountOptions:
        - noatime
        - nfsvers=4.1
driver:
    mountPermissions: 0
feature:
    enableFSGroupPolicy: true
sops:
    lastmodified: "2025-09-23T20:49:33Z"
    mac: ENC[AES256_GCM,data:PzR0Bd7Zri4gjpaSaeouJxSJbUP8f3dHuzuNlXm7q0B3SgTExHAYWT+YQ4S1QZPibE7LcPMln8Al+ac2TtVaIYD+voISUMt1+w6bqA2RmO0ZbF0mOqMiMTnWtbvCI5b/8g5+lYQRWt+5k6Lwtl5qxbdEeaBKa9qYpNw/DoEDwlM=,iv:T2XcsYVdQUGrjbleoAfcZXmS/m+kh1VcdMpU6TAMnX8=,tag:eWpR8XjOdSujxaz5aeWz2Q==,type:str]
    pgp:
        - created_at: "2025-09-23T20:49:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ/+IMPmEpFfZkMC65azxf/qhbBg6z2rVC5Yjb2x0F9vhiCS
            nbyrAe1jTi5sLXBFAeB3NSR4NAdmuicJMIVcCTBbIQFOdGgE9zh62ZK3nR32JabJ
            cPIiQLI0N3Mk3Jgmll2m2Zfj4FoanDYm3rJ2mAaKRhqN+txjHCv6bfTMcWfx09FZ
            QjZbtU3frO+5dbSv7SAvQGpk2ehZJ/zcbhnwMv/wD8uMj9fjRLdhP4yBqDDapiL5
            IvHkEZhm0egy6dYx2KsM17j31GbA+b74GU1+2+OiZI8CVym8ZqYjHTwMGYjSQrmF
            v5DqpNrmmq0iumkRkjwYD1z6VCRJTWaSgUplfUoJnXGx8Grgmh7TqTBzAH2LlkR/
            lqqOo1+GydP1H292AQ21JMTEUoTjbVSJgYDZo+FgfbWIWQMa3DfPx5byC1cL1iQY
            kIJHkJ5k6NyPzJAF88Wah0dGlUx7IQ8wVZ8T43hf7VaeU1KoLucQfBiSau068cUn
            zekMh0apT3PadC3w5t5yia+gl4acy6PdpyqFdqEE1CahsIxr8PzFIa3c9lyzkr+E
            /naeDLQT0akEnRUnvSFLYEwo9TD+pA63eGAMg0fxNtvBpn0l7T9ygyw70ERqyOGk
            RixYAOwemlFKm4vsJa8Om3vE8chZ70z9e50/bx+kybGgTWKR6251AWU/yCxQd5HS
            XgFgCrzXAVInmOTNqpafadWJloLrMh9ukeDS2eNIeTe+rbRL9z1iWnBWnJSJ0RBr
            RYagnwWcQTdxi13qUQcxFGynYZGa703r2/yvCnE0iDVU44IJvWr2B9PW0wnjOSI=
            =NHP9
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
