common:
    ingress:
        enabled: true
        hostName: glance.lan
        tls:
            enabled: false
    persistence:
        enabled: true
    configMap:
        enabled: true
        data:
            - name: config
              mountPath: /mnt
              data:
                - content:
                    glance.yml: ENC[AES256_GCM,data:/7Dc+Lx6sucJkVz7mpbleNWLShKTq6EnDJ1du6IOCJmkYFkA5xQxaUHLIHeSiPNaxO1c40hdFb2lsyKIPqxd4lY7/VmRLyXUoUj/KFjsgRxADc57N7oOrjUObXrxClN/Pwl7+RatQd1uK7MxKcWgr+8sxgSpGn/N7HQp3gPkCKCQQpZr9yqWtMEROyWoXhOJikxa25jksky+QmZmmihNM0F8IDMRcfH521x9wRaj/LqaHX2mtpeMO3/opkeWhOjI6ZLjMc86SZb25E8z8qk1VLpFPYC3X7fEjRA++bIvQwITFk5xj7G7EatDhAfm096aGZ0wBgK+VyxeKgENswbCBZ4mz8t10ncm9yafAls+gUFV2WexiBFZGPudQP19C8W2f5uk3Q6Fl4JdaGenV9GGOPZpv6xTuhZMzdMQDP2BXsEFQqZSk+AvoKdBLCzki+/5rFMnNlGb9ApY/nTmCGHXcc/QQZ7GlRaup66jy1C3LnzhbAeJqW40ICwxqS1+rNzWJolsrdORMougxK2c8hVJVGjRgLIRKIAiQIx56mRA2phPejmTlZBBF+8uVyDCoSaXLuBddQoGcqUXyhBqT+eHmTBTEzYzr5M94nJxoa5VabSL8x1a0Q29yPTLiJ03/p98GyXewe1GsH0xbmR/BDFnwGgoP6QwA3WywF679JTEOqsYmo9P1eUv4BEDU0OJ0OslgJBLjN29MGbfeAh85hhlQg+atn0PSZl/xHcY1Jr3HV8+qGQF7r3+hpx3eTrN+CY56eBWzHb9ldGYCGYw4mU6qIGB7flJSkeTFiExtwDGmdcEs0XND3PiIqSa/trcUwOrZEklEziN24iJ0dfRV1g0yrH3/9cuEVh1ik31TDW3OmocqqWYMFnp+2dfwtee+TyGMUWNvg1FQxDUhwUg03UkuHWl9kO+ErgpXrteQRnPHl19VbhkmHlH/Ev9r/fYduPIADEHsosHPayfEDpLEl/wTRhIAOHY0EELfyZdS0LDrfuoizEseKbT9CltvTzu3dWGHFiuEXujGVwZv8efAZJiRS9Vpt6yPU43ppykazMPquP8BvDSopBmI9itVpWJka9euJPuyAISoxhuDjRZYp7PDhIMyn0tdLsZ35Msfi2pHjq6tUhgA+RuRuDN5ZdE27vSOfQ9KbtVCP3zc3fP9nKOKfV8YB+UX2DMnfoqa8RDCtndtENZElpXcunNY7UdMM3umfHv6fpUbCFXpwNFAg9uYR4C0SoqmmguIV2xlOepEjmpmBFdMdCX5x/Zqp1hBwdC5JIdkYUfT6YmWwkwCxk2g+8BboskuM0NLS+LV8kpC7ZYW5/8a8+LdGedlffqQOozeL/Kdh8DJvwbAYBnTH+4fsq8fc1MdfFfEf/2XzaSkM5pIb0TLaez1B4H3xW0m6x1IYexzb9xRQQvXbiP8BeRycQb9eIQhcYMAxVXVh20Tqahhb7TVWko5wQJ1rfKbY3f4HTCPedzi4fENsZjFnd8pm0q1AQNNn8zQFQP/rQhInNKbE6JodjSJYLKpUI1ShOOtU7unRRo73/4goBRg9j1gWxygu5rt/93pqaw78D+Sky9dU1i4IFDLt5Ffd+aJ6wAl1WexrVB7XKSNuJhjawytWpy9ImEVEjxptABhrK0e53dJRtuUlN6c9h/+4x7iK7ep2SN1uC7OdiB45jwJSipJo42l2MAqxMNP9n3av87GFRsFrpleyh8P6hXy6o=,iv:7ULM0DYOMNWucjMWQCtHeaWRS1NKNDjJr86dAG7GqeM=,tag:4aQRymG6R9zsGyNwhhatZw==,type:str]
sops:
    lastmodified: "2026-08-26T19:28:05Z"
    mac: ENC[AES256_GCM,data:NMSh4BgANc9rg24NjwMWiS1saxhqjnNNEpSYu1RryZyws+nKExn8sl7+hG8TBPtj3SAMbT4C2M/XJd57xpbEhrW0HfIXVgfW3hc7qcdsbKTCpJ3sTW4+NQDQ9n7J2pKIIOKQORnJnbr2HU+6Cff/vxFoDdkOED/9MylldHV3sOI=,iv:L2m+w2flfc4nIhUYtd8Gl8MPu2lCVx7VvR9+3kC1bUY=,tag:QDcVNCVTce0FfuUKdKLqaQ==,type:str]
    pgp:
        - created_at: "2026-08-26T19:28:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//b/Zd4NDQp+q/69SarfsYcUat2m6V/WW52Qp+DCmBMZDV
            zsuMVtsyALqU3O6DqWTwk7SSyTiaqyu7F7LdIUWb3kWvwJJ9akk25i1UhZtNjZBr
            ENOT30NdvPtJdvlgQzJiLJSMMQglxLgwqR2DiKcxEETqNm1H1+Aw9/QBJloTbFxv
            4OXDinbLX5hhHDwZGgX33FWI0lvO3s+j9PfLa8wD6RQtACrQogOlcs1VgjbcSj3M
            ifEuujHPvFsfuV3afzBR4v/qKQ1uTHJv95WXuMjuQ/2qVSPUHVk6zclJ9xVbPP67
            FUvsC3dxGzbxuXu1Ya3uMIiSfvsZAcwWr4pzr1KCg4Fr1IRfi7NNiJ4xqOWzULZK
            EiGYbiCGvT5MFL4StKXVEpIC5xp1IWJB2/ZVY4JI3+fofeCtV+OzXekmygja0BEE
            eJqZxrTmCACVG7Tu7OHHQSVK4M7cLyDwz6sUKyOlrtNzuds2oTVbi7jUYMUDDLmo
            htSQQNlnJnN0YbHKyVy8I8xrz7qUfB2vTqEqZIAinEDZiVWCz2r4SBvTFNAWCFYV
            u5xEIwMiz44FJ3Er8NqUlyXuRvfU6HmDoE4FrIV8NWuQ+lMWdW6wQsLxxwkb51Yf
            xAtbh6pn1mup+48iKG7F17PJYku2nJXEk0MeJKBbrLClCM/ZR3180+os8273NgHS
            XgExP0QBEpEG9OR7dKk+AZMx1sHIqC4o9L/YXPYpPXEmlxQt9laZXwZrOOL6Z2Lv
            ZA3zBVyb2ENkGkeKY8rzVJKs3pfh5MSDF6BQNW+nJMf5jlgGnBsBTAGFRMlRugA=
            =AQJC
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
