repos:
  - repo: local
    hooks:
      - id: encrypt-files
        name: encrypt files
        entry: .pre-commit-sops.sh
        language: script
        pass_filenames: true
      - id: generate-dependabot
        name: generate dependabot
        entry: generate-dependabot.sh
        language: script
        pass_filenames: false
      - id: generate-docker-swarmcd
        name: generate docker swarmcd
        entry: generate-docker-swarmcd.sh
        language: script
        pass_filenames: false
