creation_rules:
  - path_regex: .*values.yaml$
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    pgp: DC6910268E657FF70BA7EC289974494E76938DDC
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: DC6910268E657FF70BA7EC289974494E76938DDC
