services:
  hedgedoc-database:
    image: postgres:11.6-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.10.0
    networks:
      - default
      - proxy
    env_file:
      - .env
    environment:
      - CMD_USECDN=false
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_DOMAIN=md.vhaudiquet.fr
      - CMD_PROTOCOL_USESSL=true
    depends_on:
      - hedgedoc-database
    ports:
      - "3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
      - upload-data:/hedgedoc/public/uploads
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hedgedoc.rule=Host(`md.vhaudiquet.fr`)"
      - "traefik.http.routers.hedgedoc.entrypoints=http"

volumes:
  database-data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/app/codimd/db'
  upload-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/codimd/uploads'

networks:
  proxy:
    external: true
    name: proxy
