apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openclaw-operator
  namespace: openclaw-operator-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/paperclipinc/charts
