apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vhaudiquet-fr
  namespace: vhaudiquet-fr
spec:
  interval: 1m
  url: https://git.vhaudiquet.fr/api/packages/vhaudiquet/helm
