# CloudPirates Redis values for Paperless
architecture: standalone
auth:
    enabled: false
persistence:
    enabled: true
    size: 1Gi
    accessModes:
        - ReadWriteOnce
resources:
    requests:
        cpu: 50m
        memory: 64Mi
    limits:
        cpu: 500m
        memory: 256Mi
sops:
    lastmodified: "2026-08-26T19:28:04Z"
    mac: ENC[AES256_GCM,data:e9wC+D0aamMPY51uNvegO9qcFjZqjow7uprHYBQxf+iU4PIsKAwPIeLnsqYKd8CWgeAsHmxGkxgiLmbxB86bbmjl8VfwZyRvqXOSfMZZOCUS5w5Gn/upsQFhRttfmq6YNzkOV3KQbLuBTGQPoMtAAnCLmDKjVZlCxYt+8ViMlHY=,iv:qbDyQ3weywhJx3gmveLY7t/R1+5zLPHcOaU51Jh0XWk=,tag:C7LkgjkT6UrFqihDATyl4w==,type:str]
    pgp:
        - created_at: "2026-08-26T19:28:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ/8D7I7gMnDoJLyj371WDayeV2SVos6gEscbIVFd9U+hiYA
            qMHxRheqVpIzAEmBxhR/OnFMcYhUB+rBO18Hlvu2+dG3DxN5cemeJEwvVRC1v4uJ
            RZfV0kHCLo3VKLGXJ9Wyc1fnKYYbVy/7qjXBY6Kbl/+1/FYRQ4K8Qh2jBhnkFy1o
            yZlRWKcdz/JP8bPr6t1Axv00dV8L6jYQ1wVE+0HijVnzromOhVxemp/xpQ2Ftp1q
            CJQDrdYTPI997zGFiy1TdR21f3ruCIS20mjLuc6tKjwAP8KFSDkXrtcmfrBixnU5
            rmbDfMDuA0CNTvfYQQeFQPRn1X7gMDFl9p/Uv5hiV3LuQslXx60UjQAN63a8z/ry
            DwjIAjXIEpE6PKTKols7WD96KmDy7Z730YcZfO/28BYcANxOLaPzGLK3ztQSYpLv
            Cnk1F6w7Vzab6D2SAmUot6Zgg9va3V2/DQmJ9yv7MgdHhvfd2kkWf8PKNntc0QaG
            hEs8dwOpKmZjCVVgA8C8enHZ3MmIXqfC/KU8boOeRSaEOG2PXwpuyTwoWvkA5+Ge
            kDhyBWKV5sOBMvXqGqyDHy8F0K22Dz9kDbP6qtSkGjeJJ02LVik6GcW4V58N7Ebp
            7k9z19CPDnjF1QGc3ymiGklkDMpLJ3Jwpytq/E7RgqRtMkflya1rAO9Os2ruKqbS
            XgF+lvlfuoJBtHmSVe1llhfqcCIdQHEdibDSUhTcNG3twoCPGJU9p6clHRTohz6M
            kitS/B0CRR98eNIjt6lSp03FNQRrVpLAgbAHBMZ9Q74QSdNTAvhR17dYWRelXe8=
            =SjtQ
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
