services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    networks:
      - default
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=transmission
      - PASS=transmission
      - HOST_WHITELIST=transmission.local
    volumes:
      - config:/config
      - downloads:/mediadl
    ports:
      - '9091'
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local`)"

volumes:
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/transmission/config'
  downloads:
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.local'
      device: ':/mnt/media/download'


networks:
  proxy:
    external: true
    name: proxy
