services:
  traefik:
    image: traefik:3.5
    command: 
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - target: 80
        published: 80
        mode: host
      - "8080"
    networks:
      - default
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /root/homeprod/docker/infrastructure/network/traefik/traefik.yml
        target: /etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  proxy:
    name: proxy
