services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - target: 1883
        published: 1883
        mode: host
      - "9001:9001"
    volumes:
      - data:/mosquitto/data
      - config:/mosquitto/config

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/mosquitto/data'
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/mosquitto/config'
