apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      chart: gitea
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: gitea-values
