replicaCount: 1
image:
    repository: coredns/coredns
    tag: 1.12.0
    pullPolicy: IfNotPresent
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 50m
        memory: 64Mi
serviceType: ClusterIP
service:
    annotations:
        io.cilium/lb-ipam-ips: ""
servers:
    - zones:
        - zone: lan
      port: 53
      plugins:
        - name: errors
        - name: health
          configBlock: lameduck 5s
        - name: ready
        - name: etcd
          parameters: lan
          configBlock: |-
            path /skydns
            endpoint http://etcd.coredns.svc.cluster.local:2379
            fallthrough
        - name: file
          parameters: /etc/coredns/zones/lan.zone
          configBlock: reload 10s
        - name: cache
          parameters: 30
        - name: loadbalance
        - name: log
extraVolumeMounts:
    - name: zone-config
      mountPath: /etc/coredns/zones
      readOnly: true
extraVolumes:
    - name: zone-config
      configMap:
        name: coredns-lan-zone
sops:
    lastmodified: "2026-05-02T14:52:11Z"
    mac: ENC[AES256_GCM,data:oXGy2tIQBn/ntx2HwpYohfVqmhqFs1zcWZB0LJbu2EjIpv5kkBtlaJyOb5i0GfI9bqktRWRWTroOt5FziTAXlu92wvBgKjjIyiCJxfqJTqMXgXQfDWDhVMd+3M3Ph/NQXgsIELPBLEWHoIj3faL/6SpVaJGXP/hVZnCv50gg3OM=,iv:N8uAC80j2D2Wyxpzd1Fg0LvG0YxUqZvfSNxQ1nOLbEU=,tag:VTY/sg/p7briYpu03+8kAA==,type:str]
    pgp:
        - created_at: "2026-05-02T14:52:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//fjjJ8ygat08uSOx7/p/eRG/6jL9TEQCqfc5hJ/I3GxsJ
            +uS8gYfkjZNBxnxt49YJPWAmra29XWx7M17HJLxW23eMCGuNp1EhanCEBrGOBM1I
            Jf5I5sLQOi902Radwy6cUXo6gieQy0Dm/3t4uj4O8O6fiBgjPZkdMKfUgB3dfZq0
            gkZRYARoa5E19BYbWT5d4HQGf1d6suk9CbWJtauiCvS0GUFEzdoQRdD3QWy0Vdf1
            H4KgKk3CqK4VOnwTYYzlWzSl5NlN0BnmRMGamepEUmG5kygQlcIUf6eJ9T1+wgPy
            cUODeWJ/VnTzQs8mriBn/2GZTtjZIKZdoq/psX9/NNbRpDJX/qdKrJsAjOTdNU2+
            wmHI7OJnR3L00KpDR/ZJSjGyyNHpv5GcIwMLkpR7RnBhyWjQ7BdNgbtqWn7Nou2l
            wo1KwY8O0bYgHC1wbLHXrRM1TyJ2GuXwytfREveEi+xLKWLzbEr0tJTYoYBQC79s
            MtBcuDaZ2ZYd0LVj2QQlakKXOimSU+yVePJ7HQIyeUszU+vUHreUfTmBjGRZL+1w
            dYdO0TWOx/gbscjcS5LfLLoYyVpP6pIsPYpKHfb9QRIpRlwgsk2/T/+d11pVj4Gl
            zoET/iApb4Fwn3kyPHJsrFpZ3b2ZckxlaF1fPwReMHcsM/CVufLyCr5iifrxJe3S
            XgH75OoeBcuu0VbsYXXVHNNTGy4QC8oyAQOSe17ardnhSbs7jrL8SYe74MLI/xY0
            Pe6oYF6CKUJimHq3OgIaf0PRaDJxUiVKi08/PxFiJOl3gHulQhhsj0aep/6etmY=
            =E5/1
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
