replicaCount: 1
image:
    repository: coredns/coredns
    tag: 1.12.0
    pullPolicy: IfNotPresent
deployment:
    dnsPolicy: ClusterFirst
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 50m
        memory: 64Mi
serviceType: ClusterIP
service:
    annotations:
        io.cilium/lb-ipam-ips: ""
servers:
    - zones:
        - zone: cluster.local
      port: 53
      plugins:
        - name: kubernetes
          parameters: cluster.local in-addr.arpa ip6.arpa
          configBlock: |-
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
    - zones:
        - zone: .
      port: 53
      plugins:
        - name: errors
        - name: health
          configBlock: lameduck 5s
        - name: ready
        - name: debug
        - name: etcd
          parameters: lan
          configBlock: |-
            path /skydns
            endpoint http://etcd.coredns.svc.cluster.local:2379
            fallthrough
        - name: file
          parameters: /etc/coredns/zones/lan.zone lan
          configBlock: reload 10s
        - name: cache
          parameters: 30
        - name: loadbalance
        - name: log
extraVolumeMounts:
    - name: zone-config
      mountPath: /etc/coredns/zones
      readOnly: true
extraVolumes:
    - name: zone-config
      configMap:
        name: coredns-lan-zone
sops:
    lastmodified: "2026-05-02T16:24:22Z"
    mac: ENC[AES256_GCM,data:P3COCTltq31Zx+xWD1S5m42yTwiEsj+8NFAUxIp1sYtCpwObeZOMhHMsbbycUOkQ+yRY78SW8+x4avMMTyI97uCFw8IYBMlFN00aaV/1di5jGP8A6d7i0Ma72P/sm2VGGuADQF5GfGiRhghdvIz8uuAU/1u3jjENIHm3X69Pfrs=,iv:l0HrWPnPyzJh/dbNl2IbfeW8BifLa8UV9ZwYAlZxuqs=,tag:isFt1Q2XczbrAtfJUHvqcw==,type:str]
    pgp:
        - created_at: "2026-05-02T16:24:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiARAAjq/E1wLzVCjStu6WmEDNnEwwwYxjhDqqKyC/UaEPftv4
            unAEazPIbo6qSYITOXy8/nO+rHC4gCGIBpi5iREo6cO58g4oJrKfqrVyR+JhokZa
            tDZ0qwQjvHjx17JxVy+LRA6D578KlGN6jL/fhdX3vqkS9b7QLW5DhZiUZbA8shl/
            o3qOS6hep9fRMXFBzemAfXWnBJqqeQZDEx4J1sHzgH8YltfRr4L7zE9ctBdt9Ksc
            r8vnwuttUT2OtWIt1WNeILbPGzHNF7o8Ll1sy1dLciSqWbGzz31Y2EC8CqwDVfoq
            eL+kl/ScZDHW6uLmuwSrBituV4Vc1xPRB/B6AFc2FC6TC94xSxULuqpfriepxCs3
            Vz3Nh7szg0aoKecNrwanKYixoOZSaYZTNBdvUQNLUpmdX6VAhTPKBlivQw0LjkSW
            7uo1lpnJU39xYK9uYGYschfWybIQmMsxdtz0G/2hl/iPDiUwFddRj6v+SsVWYnz5
            /kU+ytkuPysLSZ0kfMyFhsay3h/5DJzCWexXL4q7LgEOasPiRgEPPOK6v9VmKC1h
            EaV2lyVIV9zJHB2/mi3f1cIB4XNNZnNmv5PVYR3ROFa6bSuOgH+mt3ApHh7LHPdK
            uHWl/GhyiQkcM5EHG14IPqjkYn6KGKutvacx+vH78pxioCKzRDLIlDCKlrFfNpTS
            XgFBlYuqR1fVD5EYPCbbgXC6bVi4k7GHqz7QkrHattKLjM5cteGoADepdTLNcaDu
            2laxXxJizphBGmSL4v63Cs9uL5ps+nvWbbAOwyZFDybpZw5dTPnPPIwE1Gc47H8=
            =kfX7
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
