replicaCount: 1
image:
    repository: coredns/coredns
    tag: 1.12.0
    pullPolicy: IfNotPresent
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 50m
        memory: 64Mi
serviceType: ClusterIP
service:
    annotations:
        io.cilium/lb-ipam-ips: ""
servers:
    - zones:
        - zone: lan
      port: 53
      plugins:
        - name: errors
        - name: health
          configBlock: lameduck 5s
        - name: ready
        - name: debug
        - name: etcd
          parameters: lan
          configBlock: |-
            path /skydns
            endpoint http://etcd.coredns.svc.cluster.local:2379
            fallthrough
        - name: file
          parameters: /etc/coredns/zones/lan.zone lan
          configBlock: |-
            reload 10s
            fallthrough
        - name: cache
          parameters: 30
        - name: loadbalance
        - name: log
extraVolumeMounts:
    - name: zone-config
      mountPath: /etc/coredns/zones
      readOnly: true
extraVolumes:
    - name: zone-config
      configMap:
        name: coredns-lan-zone
sops:
    lastmodified: "2026-05-02T15:23:06Z"
    mac: ENC[AES256_GCM,data:Z9RW7y8WSSTZSNKHWxzh9UEr+Q2f5ju1xmwRklTtZq8ISlDubZ+/aTv14tiKrOciqxjC+oNIuAYtAi1nlIAW3k7qbyTBwEMKMoKtKHeOFRhCuLLe4GPDbzBcmyNbXYeRIX2sIGgm9kkRBZvFlb4E9eAUIRaVV1UgXsyBRvDepME=,iv:/nTs0t1CWceJHnhNXtloa2TyNi6yI6kAvjcWM371rac=,tag:yLOQiG9K58f9O5ktNwIwyQ==,type:str]
    pgp:
        - created_at: "2026-05-02T15:23:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//ZKiDOmXL2Gs4rx/r41KTzxudbSAGOrHroluRWDhhTlQ6
            +w2N8zJkUqNuhiz4Gx4KufFe6kOAElV5q2g8QDg+B/N//1EVb/XGRN/Msrsh+nBR
            IFXM9wTAIX/bQ7/VUdqyotkj3IY3siqwlPUPfq5et9LbMtHByIqarExFR1386XX9
            dAWmfR2R1f0ZxMmW7N+59b3J9PR8YnslsUFjtS7C/g5bpuAIpQYWshRBE5i6o0qT
            5/MEHGrf3idSWFw+Q/7Ai6A11lhSvVASwSmQNq9N1p8DQaGuzOnUjn/n5T5oQVwa
            koUU83JZgUHWdIHq6gYbqyTdMId0i5E44xqr7fFAJcP79F5rK5JYGrrySBl5UI0V
            8tDkgWXLaR/Vq0fyjFUwW8yXZOaPMdUAYnYhLHDsEa+5Fq1cVVKlFhPVg3FT/SQR
            kEIRtfxcGrXj8S+a+sKVC3B2dG+G+QaZOxXd9Rb3vD6ZwkHyrfNmw3FxRrCRzsiQ
            fYE3Q8v38cbhwnmVF8aPc0rNss87b/Vs8dtFGLc4ZE6B+axlCjCCrqL3Plm3fzi8
            bWJNOSt1+4AwOPv33CDl1wEBz6RLn3E5r4cgvDuWzXGdAoWg4pwj9Nyxs3XtVn1+
            hXTkkcEU/8MKL+CT8JeuIt8/MDjRxdCSmlRz05660yQVWs6if4CMPbuWFU9ZT/jS
            XgFSm/kaWTOOrTKTFAisWs/GUZpOyrRuqG6W9M32tyFEpjxXvec+4hehA/lz3ylo
            UW7z31WZtyPsoI+LXo1rfbH2Xg14GinW2vkgtBHf/E75mpt/4IbCgdfGsky/N74=
            =0svn
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
