apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      chart: harbor
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: harbor-values
