ingressRoute:
    main:
        enabled: true
        hosts:
            - host: dashy.lan
              paths:
                - path: /
                  pathType: prefix
sops:
    lastmodified: "2026-01-18T00:16:51Z"
    mac: ENC[AES256_GCM,data:J8ztKcQ+hK/LQT4H8iygc7tfjc8H7pMRRF/38Ly1r3SbrYZ2Yo79aUhVjkZUuO46OSNPgxn5MY/Krvjs087kVruxihWFO4tJ1mP6XIf5qe26sSmifEX9v1/ZnvGDB9NbMx0ResrhqqyB8uZo5cpcFuYF2MA5fZO1eGy71kJu4rU=,iv:eQdxbqyCT+oLQvjwGUK/8volvO0CRMeqyorn58qslq0=,tag:+nNgbpNJauZQFhdws4C1GA==,type:str]
    pgp:
        - created_at: "2026-01-18T00:16:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ/8C/4cUpuI+wXwawD1p5No5vPiiMFGf7tQUxtzIwjqpNc9
            8dpNnvk4NFvuntrw/4+o5IgnFmxBjR41CgmG8U9YxBkxKeK13ia4Z31dfFWP28Fx
            17Kvn8mZBpQhslTTaNCfqSrH2dDqraQwyCS3ZNOYOKpj+4bHAaaX8fruFXrogqQM
            gCyo2icY5Nwo5RA730c0X5mFh7C/DCwXP+Uj9YlEWpY0otaHhX/HeNnEUnH4egMB
            QITy0ouCWtrGwW1HcKl+McrFA9Ic/qw+tm+terllPkqxfDa1O9B1rsh8o1pTcYaM
            JzZyrZsgpzI2J9Zp2Sb4qQ8Wlb/cuDZQLvK1CQ3Vc45qUcrGwgINaWdmzM9bv/ZA
            hAhzGE+7vAS02q16OG2gRIujChlL95IlRMIfOF9sTglcE0j4N1/Nc9CgxP8MUO+6
            zwoY+MQ5urdPadAB4WSutRneiDcLWmn24XKI44eJ/Vd3S/GoOq7LCNy9sU/Fpymo
            cc9xfCCNgtNsErTC4PIKS9z5hfYXIvRs8sTzvUS7vfbNDv1dSgxagl79YiQoiJ/g
            JgoS7mBvpV5DwyXjsuUlyjSrz3QjvltajX0T12ahHF/ercBE3ddGirUDUDYeHu32
            +LaHFW84pDFRPI8OAJ6bN3M0wa+k1rToCOJMFSXGddbIieGB78SmVAjgYrvhL2TS
            XgHRMDYdkgHw8s47NaFH08Rb2yMUmQCY1CF1IGZpeDuKADhtGki6c46FJh/qLpwU
            MXwdeyhSgZle7Orr3rrJBYD6xK2q9jg07bsq7TwOL98Y8BkWf/hLHd5jAMzz01I=
            =XjBN
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
