ingress:
    enabled: true
    hosts:
        - host: umami.vhaudiquet.fr
          paths:
            - path: /
              pathType: ImplementationSpecific
sops:
    lastmodified: "2026-08-26T19:28:04Z"
    mac: ENC[AES256_GCM,data:IIlN4Eg5FbDJbQADFcU1Rf0kzv3GrvwjjmrdK1oIX2Ae5u2Wu3+iXhhzx4j6CD43R5omnKdvLVjU3RxDS56vPWuyJziBBe1Hzzl1l8AfdjF4ggS9RZqLf+50+EB7en4jVD7CXwgGBLoy+eU8UZKCeqR5Ft1sMEUcLxGMnvwVBhE=,iv:a0gk/m26Z+q1IHKH/Rdum9eCUPlWXN7qeKP0nQmkBus=,tag:F7f7XAksl3I0KAActBP+Vg==,type:str]
    pgp:
        - created_at: "2026-08-26T19:28:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ/+I3nQpvsM+0JUvNM/0Cb0H2eI3xdBXwLONzY2EE5U5Qzr
            81TyVTcKtjXVNFmo4aGUCdXPt++uzLu8X3iOzzZDJzU0IbOrs1t+/CGaHPJvVxIe
            vTYSF1A3HLr5vZCZ0y96EWV57cU59iYUEDNvXfMuzGG40JGsBiJK0fTzexqc6AnH
            8L+nWXzBnbN8rU/SnVGPyUPbqeJfy4woeIHolkFS7Iwm389CPEcPdgGQqMpBDb9Y
            GKoZEg5ZG7p7iAtwIp3tObxu87IsUQg/q3GkAyAJqDc0GTPIVKHcO+x0kbyyBas8
            bDLBVkJ3c4vR52KL8aXFnQeoB3AoihhbeLZHHr+WuNCv+9xQbQQ1mh6emehIU9IS
            YSCcEG5/k5WidzO74NY3JDLXLzYJKHTQ7MhH28YkehJJk01Con+0OM+ySvWsqJ2o
            V/hmHt/UFljt5fEOo8IFm8MTUpSmihm7HJT1FG4N0SLpSEyr8h87rA9WZpZtWYI3
            6F+tBOlXjBp5Lrl5MfGHzNS/M7zTohUSwSK/N253jUXB8sB+QKOMC/dHB/388JxW
            46E1MysidePHaxJk3M7DsXcmz4XvWESu1Xpf0bAzDrRS1VhtIHrbQdLwZ6xb9fz9
            4DphcE/o6uZjJKHS5DwisMtdmX9ibrmw98VLy4lB+sjC6hQhoPI9Ijd/qBDdSYHS
            XAFVqj4L3dEqfvOpBagoLGRiUV4f96njkEkSmAvtaenF/Ae6qPIbRjPOQv/RNC5y
            ksOXeeflYu2gVNZvfzENAU3NBYGkmto1MpPDOj0mnUN8pjNbI1SPwKkuzYdo
            =DesT
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
