services:
  excalidraw:
    image: excalidraw/excalidraw
    networks:
      - default
      - proxy
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.lan`)"

networks:
  proxy:
    name: proxy
    external: true
