services:
  mongo:
    hostname: mongo
    image: mongo:8.2.3
    restart: always
    user: root:root
    volumes:
      - bpmongo_data:/data/db:Z
      - bpmongo_config:/data/configdb:Z
    env_file: .env

  match_collector:
    image: git.vhaudiquet.fr/vhaudiquet/lolstats-match_collector:c506bad73921d1b728c2c2f48582b5a08427da49
    build: ./match_collector
    volumes:
      - bpcdragon_cache:/cdragon
    restart: "no"
    deploy:
      restart_policy:
        condition: any
        delay: '0'
        window: 20s
    env_file: .env

  frontend:
    image: git.vhaudiquet.fr/vhaudiquet/lolstats-frontend:c506bad73921d1b728c2c2f48582b5a08427da49
    build: ./frontend
    restart: always
    volumes:
      - bpcdragon_cache:/cdragon
    networks:
      - default
      - proxy
    ports:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`buildpath.win`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    env_file: .env

volumes:
  bpmongo_data:
  bpmongo_config:
  bpcdragon_cache:

networks:
  proxy:
    external: true
    name: proxy
