ingressClass:
    enabled: true
    isDefaultClass: true
service:
    loadBalancerIP: 10.2.2.6
ports:
    web:
        forwardedHeaders:
            trustedIPs:
                - 127.0.0.1/32
                - 10.0.0.0/8
# Tolerate failover node
tolerations:
    - key: ENC[AES256_GCM,data:r4uAu1ni9/Z8,iv:aKgn6DgT9XnjzmotnaEIL+WzUiQ34CazfervJwrYsdM=,tag:EeOY1YZwNCOPgHwXpas3ew==,type:str]
      operator: Equal
      value: ENC[AES256_GCM,data:b7AuKuC8Dug=,iv:dmkEkx9fnzPBOizJ+3xCQsmqSwU7wUrfG5oF9FSCCE4=,tag:vZA1OWI+W5On6bGqrZNfGQ==,type:str]
      effect: NoSchedule
    - key: ENC[AES256_GCM,data:qNeG+KkohEaTXocYL95TPDvvhhH5yTa5FEWJ3UHe3bw9F+XGew==,iv:PTnlxh9E9FKpNcdJ0kF+D6dB1MuMRq9b+wZ7zjqch8Y=,tag:UWhOdWwbYpN+fRTFVKiG3w==,type:str]
      operator: Exists
      effect: NoSchedule
# Prefer non-failover nodes in normal operation
affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                    - key: ENC[AES256_GCM,data:bXQphRUpcEmBAh8AjIpA+ZHvdw4=,iv:EgGe9ZS4evXzp5A8+LelSWKRI09e/BzLzlVEHVk9w0k=,tag:qbOp/ziUVmvpEEaZ43nTlg==,type:str]
                      operator: NotIn
                      values:
                        - "true"
sops:
    lastmodified: "2026-08-26T19:28:04Z"
    mac: ENC[AES256_GCM,data:0Vf6cvpxBOvs64aA9ldsnbgZyba1cTKd6zyFsTsLzMa9l9OLfpiNS8OmSjOlybUz1T6DgZxpDFPaLd7XbLxwaMMsCYz7pRRYA0+BEXM9B6PM0BlK3jUWKrxWPaV5KxN452BUndf5KpsD1f3n6ZvBMQos+H8fipTxnYr9S/RUmmc=,iv:FssseDQUfUfpikIy38WqCL083KZnIAIW09mntdyIImM=,tag:hly79N865OUxLOCBx+zK7g==,type:str]
    pgp:
        - created_at: "2026-08-26T19:28:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//XMQdSw3SGlu3PUrzo0xjaaGipUQgbioAJ8lCf1SP9HDm
            ghSOmLBBunRB1MfAor/F+YimAGCOlZfeObXKIxydvOPlwgrLNs58Pl/d6xBO2fs8
            ZGLrv4OEV5loII+UGAoxfOTgkP9ZXRitKceDfOLzkDhhshq1Ew6PlBaiAaMI6s2I
            CCRqKLrD7tLJ+Ax5X7Nndlrv9g4UgK1xPwsH+h+27U3z9NYrRH42nEdUqtenePUq
            tT0XhdjwcKo5g1qqZS2zptnf1WfZF4swSZPIsNV34tyOOKIQQmw0+ABVpi8GA88X
            guiJya4xgoriIHa5pNcpUnrrgOFsqc7ShCLVRep8JteJA0oKlt2i306NlT/PbsTy
            tQXQEga+IgFyis/ECa1odhKZhK5olRE0upCkzj+QHKSqJkBaeoliMSEUq9YLdwEk
            CruGUwjs39esVhaFIAv6EEbw7XtZYCx6Bn5fDlh3IQUKpd5BeoSuQgy24OBXj/xa
            CdOIRhVdTSlYSzVWoA330+F3D846/DZX/pRgueItUEXcC5F+nbS8yWLwg7+ytnGL
            DOSW88c+y9B0rnpe6YTkEXtXZkyW0LJogVjPbchCyopATy++IQhLNSIwBMpXI3Rp
            DpyHwG0CMAlSGOzVJgm7XQKI0Sd7iriVqTJYNfrkLYt4ATWZxq+Wqbi/k0OmSyfS
            XgEAJRybXAmH6KcV7W1CzKXtay/2a5LE/M8gw8BungpTMM0VY5T89OPQ1yYC0hGx
            YY/pWNt36nwoeG47lJ/HL538sq8QQWyXGrpLae4A3zyXMitdXb0pAW0OFqzBd3I=
            =z9GH
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
