image:
    repository: photoprism/photoprism
    tag: "260305"
    pullPolicy: IfNotPresent
resources:
    requests:
        cpu: 200m
        memory: 1Gi
    limits:
        cpu: "2"
        memory: 8Gi
ingress:
    main:
        enabled: true
        hosts:
            - host: photos.vhaudiquet.fr
              paths:
                - path: /
env:
    PHOTOPRISM_PUBLIC: "false"
    PHOTOPRISM_DATABASE_DRIVER: mysql
    PHOTOPRISM_STORAGE_PATH: /photoprism/storage
    PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
    PHOTOPRISM_ORIGINALS_LIMIT: 50000
    PHOTOPRISM_SITE_URL: https://photos.vhaudiquet.fr
    PHOTOPRISM_WORKERS: 1
    TZ: Europe/Paris
persistence:
    config:
        enabled: true
        mountPath: /photoprism/storage
        size: 10Gi
    originals:
        enabled: true
        type: nfs
        server: truenas.lan
        path: /mnt/main_storage/valentin/Photos
        mountPath: /photoprism/originals/photos/valentin
mariadb:
    enabled: true
    primary:
        persistence:
            enabled: true
    image:
        registry: docker.io
        repository: bitnamilegacy/mariadb
        tag: 12.0.2-debian-12-r0
sops:
    lastmodified: "2026-08-11T09:25:09Z"
    mac: ENC[AES256_GCM,data:Gjvc44UTfro130jSfI5Ceryzl1KHMmMOawmuosAqacSa4y9FfnXgmirDJkqXXYcLYeUplP12TP1v05euwcGPB12L81l2EZN2mxPbDYgoOAuoGtYqTlN3IZ1cVW5ASFWrCPEdClr0DNvtnIWctzhdue/NKV2ebZpw1wrgTwOWF7k=,iv:Hdu2l60/2VEhlNQPrWKMXV96rwkRgn8E1sHM8W7BL5Q=,tag:pwG9n9n69sIe+6fPxKgiyg==,type:str]
    pgp:
        - created_at: "2026-08-11T09:25:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//S/qbQ9OuFPkoxYkoh1r6q16kDt0A/W2DsK+mz0uPsupF
            ybzXWRkWKt0rXoKADx3jOnWicJNjVgcX4+3OISeNc29f2uOglXeXBFrp7/Kxsl34
            KKK4YeKnFLXsCcb0HIAZ9QNuk5m3qFqPDvgYlbszF9D0CgzitdAltpiNT7ckwaPq
            0/78byG3kMttTLW1Uj3Rlwm9SAdLcsUjeHSLVpFWaRXndV4TVL7QnqL1OPdIxJkc
            2/ecyPgkx4Iaonnwz+8iRAv19rQOw33cZtNjF3kTjk4xGahSc4sUf+kX69JJqrXC
            KNflyyV0K5nVye6EbfftpUSqAUfpAFNdmUK6PEVSGCi1AK9oJjb8TDuYGJDZlNDG
            +P5/WFcZ3uwcwM8syXm6M/ZoWJRvtjwV+IVV+pbeAAGzpsMzUwqikKnrjotEfPOg
            teCyTDHCyDHwr6eNclP1YptwrPPdwRbhQ1UTOPZ0spVjqWOO/V/UFYjwx4M8ENYV
            uwtRsI9fJN3K2eKZXOhtSLpkBNPkKNBKqgLn2Kx+TWA79HEWUTPaO2bpY88A7ep5
            CnDJ7PqjDYCijcNcILwmQPCYCjaQl3yIw/K2ESGDWJOOs/TZFksoDptjZ4/4Hg7l
            Hz5SMbY0/6hIVwLCpT8nIAe9fWGsu61ALJjz/pdNjRbcXJlrCtfv8lawGTJeC3/S
            XgE3i1O4BZ6syvZh4x7ROcEXuxnynZ4wbJpGOLr0fjKm/Sxp39BgkT2BxmqPGXvk
            n4pSoqI5fCVlRTkVO5Mr6SdiC4A4S31hREQycIWN1spQcJSe2s3gz3ZRDq/1izM=
            =67H6
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
