image:
    repository: photoprism/photoprism
    tag: "260305"
    pullPolicy: IfNotPresent
resources:
    requests:
        cpu: 200m
        memory: 1Gi
    limits:
        cpu: "2"
        memory: 8Gi
ingress:
    main:
        enabled: true
        hosts:
            - host: photos.vhaudiquet.fr
              paths:
                - path: /
env:
    PHOTOPRISM_PUBLIC: "false"
    PHOTOPRISM_DATABASE_DRIVER: mysql
    PHOTOPRISM_STORAGE_PATH: /photoprism/storage
    PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
    PHOTOPRISM_ORIGINALS_LIMIT: 50000
    PHOTOPRISM_SITE_URL: https://photos.vhaudiquet.fr
    PHOTOPRISM_WORKERS: 1
    TZ: Europe/Paris
persistence:
    config:
        enabled: true
        mountPath: /photoprism/storage
    originals:
        enabled: true
        type: nfs
        server: truenas.lan
        path: /mnt/main_storage/valentin/Photos
        mountPath: /photoprism/originals/photos/valentin
mariadb:
    enabled: true
    primary:
        persistence:
            enabled: true
    image:
        registry: docker.io
        repository: bitnamilegacy/mariadb
        tag: 12.0.2-debian-12-r0
sops:
    lastmodified: "2026-08-10T22:49:57Z"
    mac: ENC[AES256_GCM,data:FFRYOVuYBuoErBONj2g9+eqfTxaB84yggUSL01ipd2NsC1ec7iGKB/OWQzuJMfsjODwsVM/TNP5i97EzWrhuuUAzdZ0jAPJiKUk4W6iCxZgPALwLaybZdSOlNqj8LxDkMmKZmIAPqpSp5zWRi6SHfxKT+4okkjwqJX6hNGouqmg=,iv:Xdk/Awdo+mZF4Ot1dchk9fYenDRwmFwRGJUg220CEt4=,tag:u3ZRb8uGHLMI6Qi5dPuc4g==,type:str]
    pgp:
        - created_at: "2026-08-10T22:49:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//cCJAdcIQmDnVIHXnrJAjD0NwVUMPhb/KwAjB2edJhdc6
            s6mCif8u9zNWMIcaTqauFxKDz8Ghe5IfjpOmibBB2z7q9J5uvOGHk1ZNGyzY6H+1
            Bop3klhWHrD6U3+HVIXnpDXPxCvbRCaUTlbCdWVRd0BAsJdN50tUGSwjV1zKPgRT
            gJ9GhdnMsXp1DGR4FG5tPthtwOvxzNc3Ep+YouI09umrL61tafkX4KVx734aZ7Ze
            bthdLsD3tjxaXUTozgVhF77KuelR1rBn6Q83PQ+8FJpMCC8j8GHe36StsG6t/V++
            vEUjRWRMn6/e3Cy/cCtHDeeIuzKeeQQbRTKw0ioMFXhDluDh3cKcRtyrl7qGak97
            5OH27PlD6DqJOZ+JF+2dopCmjTB0Nm6crqM5+TzSg82XIaPj59iZeG5bu+PYMhbs
            93pDiclH02Z9wLclgi/jr4jXZRuL8HuvFARlG7ruN0uvUnvLo7qPxRmz9T7w/zd6
            Lt353yZzqwtwORlWC+cOWU5QUQN7Nm5gwj1v0lpCOmrxWcGiDskki7Pl9U/r7wMq
            ZW9c7MG3C9ZNt2ebxdyMl+7apvyeb2zwEh9QymSMvK6NjMsmnlS4MdA5FspgjSGQ
            9eEbRu8vxDOR0abj4Y0eMOiGiK4kaimkM4vQPQ02UoL9t4RupCP/dAhOmN+U9T3S
            XAEkuRlrWbxw68jOa5rK3QQ5gUyq+W6Q8rlVVKjcQAHd8RcIo0Kh9j2EypdgbNqX
            XRdjAJe2LN58WEgCIBk2ODJFZyIVpGHablT/ZXd9KLM+GF+pPJGHJ/nr9GM9
            =RAON
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
