# Provider API keys for the OpenClaw instance.
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
    namespace: openclaw
type: Opaque
stringData:
    CHUTES_API_KEY: ENC[AES256_GCM,data:Q+rolk3ZLF3lIEcGUcQYrJe0G0Eq7o+aafqK3wZfKnNxi4UiB5NM6+KcKbKi7FL4UeoMC2MQ+HuszJWfC+X5i4ADGzW5y3CAqMoOblgmjvN1qDWRc7zog1bKBqeHuDfiJn3KjUXf,iv:KCwxCRZqjO9qz4mI7NvEiY44Evk2mPB2aiDwzhcV+PI=,tag:C4EyScSpzFIpTIYPt7nBgQ==,type:str]
    #ENC[AES256_GCM,data:dMUyQ2WCohbYG03WYtOu7ifCobP/HacAO3ag+TWFYYTe9j3stuZb54MwfA==,iv:R4nhUGdCaWZOizJY8ggMNhQWi9f8p+KCqqSBUn8+yRY=,tag:hT6jS5kDLyBlat/LunpePQ==,type:comment]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:bW8Gn7DVlbWlouZWyhAsMsUc0Zk=,iv:PGY3U+wsMuy0yF51c6SpreDEGTismFZnmankuzXqMhM=,tag:9iD1Svx3ls6nw7cThojclg==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:ssLNISDNPEdpHqKsutc=,iv:bETkOG2yKtm9PrSCh7VgUfjPXzeIW/yIdPEsrzT76yE=,tag:AdRW8jnr/+Nh1RoqbBHRAQ==,type:str]
sops:
    lastmodified: "2026-08-24T12:01:23Z"
    mac: ENC[AES256_GCM,data:Rl1yVrIdYsBTaMMz0a9jEYQ7uVxvDBrmWCmFvGcyUQKr4Yfq56gaRMHItabgu2Vsch0o2X7ljeeTD75WoWeBhV51ne1TZo/E3x4fRl05Oz54bDF/59VUbP184ZqI9pw/WEVyumUtOyIwvBpsmkutryuE1aTzPMIz45YiwMctDrE=,iv:wwIVKBmxQiEauSeyUQ4F+oQHVKhcDDQDW4Kaxy0eVVA=,tag:Y4EmW0KjtGZsZ7vfDLCoWg==,type:str]
    pgp:
        - created_at: "2026-08-24T12:01:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//UJlw8rwq1mw4f6ePa3uCpVxTiCFFFjOdgOj0wsn1WXv6
            k2fpGPV1JwIFj4Wj5AL7EqWH4iII5uxqft6XykjyhmXL2FHqO8ZN4Q/PIDpgakuF
            le256k8KbhuVjUWjtZ73pGYUkB3X9ZBBIkh6XtHVtMaOpJc2mtekuZ5PWv3YhRGd
            v/jswjzuVtjFoG4n4yimOXTQgN3HtiL08eznurRf9dz9X9s7pGI8pKqQk7cGiBv9
            EnczRcXnTvJKVfjKAQeEsr4KGvhhrJMxtH4laSUu0xBabV8UEzuqC0q71gSBtmXr
            5eHg5iFXjmcn1uXHYkKreEPkNTdh7hz3gW3qFJpRTtwYjTZzDjytoP6XVSq+avpS
            kd4iqWeS4YFTFyMfPVRLZg9TJTTAXhSlhvx7qXUPOuKtuGaoEJY67F/tnIB2WEE+
            WCgiWqsPGoXKEFI6Le7NrjsRnhJ3FLCnkd+kal8pypJOjgmJMEn8Jd1mfVxHY5gR
            jk5wgRu38zUwnOSPiee2N1LsxphQCFazP3iNn3VXUyQ8hqAxilyD6gCUz2TNBEls
            pZLFNrTdPb4Wz+hHyrXfMXW1zL5+1rUbdj6h1JFxJwg6ZC0togiFwIJrMgTexZE5
            BLOM5xwqPEaXVe/0EdgHl2borMvhqLQkS1j8gOjMceH8hUPM6FWU/PxjvsfhlMbS
            XgHJYRd0rrlzvBDh1AbAhzqo2kP01eLXEEnln6u54G70TuBxD752B2EsJRFII+ru
            b/UgHWJtc+sAESED9bHzFCoTs9QXyMuAuRrMUHtpkSF8T4DyW7j8fFcS+C7FuDs=
            =2HcA
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(data|stringData|.*key|.*crt)$
    version: 3.10.2
