# Provider API keys for the OpenClaw instance.
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
    namespace: openclaw
type: Opaque
stringData:
    CHUTES_API_KEY: ENC[AES256_GCM,data:oTKKBNoJK9y9W6a7j8BYlorsaxiW+6a5ZUXAQvkCo17QV6XSyk6JTSyD+2q3RrdJ6M1oU1EYfz187boW0NxipAV6emyg0W8KTgaoz7g5bczh8i1tkSbtQFR2yXemnYZRanFXAcll,iv:kT/t1rL03b8XpxBuyqULkb8NQS9EHDq1HCFUXsJeyFw=,tag:VUicjcv8UDV4Ar7JZBiZcw==,type:str]
    #ENC[AES256_GCM,data:zrcd7oMQVkQvN9o5Uuez51+nOY2f/pk2i4tU0Vptl4RLN2m3UiO2gli5pA==,iv:wb8SqVcYbRABqow+vZnzhEXv9m6Fa/mEDYz+dj+COmo=,tag:B8ms+oHlqWxiKwUe2vT+NA==,type:comment]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:T1S3nBNjvF2wY0S48DaGhStPUC0=,iv:uYFPix9QfYR3mdJO98pdnKRUACe3NP6YjU+7GOxWNV0=,tag:ifimYZeItSWGNthcDlLbAQ==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:ny6xflUytsTgmNEBIFw=,iv:rOyJ+o8Fs9pdyH8pfC8hTw1mdf+pcPgrrOZSGNv7igY=,tag:3xw+p29WwiP7KTg05J9xYQ==,type:str]
sops:
    lastmodified: "2026-08-26T19:31:53Z"
    mac: ENC[AES256_GCM,data:cNPNGuGkXRFm6uvie1cXLc+d6KhywAcg44ShjXWXSLlZOjKw6qu3nyin3Soe4/bHOy0SRj1E4p+aCGL/5l80Q9rDC6LSTTRMcJIn4l6fjq5+4y3nxmgiOVTELSD5+xOahpbXHTHugl4vEW0SV3ASqkE5NNmtsMYhJqKI/74oKWc=,iv:6LrsmFoheDMXLEjrsSc2b9Ns/7cU/IUqPHyTl+T5Vys=,tag:eazTmu1t4Xvc9+B9+f/P8g==,type:str]
    pgp:
        - created_at: "2026-08-26T19:31:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//a+e4JtcGkgG6B5P0OJ01fMbFzJj/PpBhmhUDKOggnjrO
            aLANNIHjmTnkSRWHAwIQJlsveE4oko/uTkZE4CULeszcAjeGdQHBaGNCxgcoiLJN
            D38IP8v+4EiWcU7ynXl1tibUkI9JgZmeP6LNErioV0IbRiaWxqYHh5FYZ8D2WAJq
            kZ4cGtqNjclcsxAhdbjpTLX7IVcJeIDEHoWoffRPW4/v6lIrfapUrA2wlxnm/Hvm
            LIvYxDiZvRafe4tBu4j9KPzyiwJvAkTnWwBjDTFn8te9OzsigOYQEcMHYWNDMZxv
            msIYdFyQnaJpsNd92uhRMMR8q7OqXnt6sAM2HURRoau0CIMwincgAHCRD49lPHfS
            e5qufYjaHHnLMgELu+4G0DUGMhVAisT7R5/QETl2kDSCZEcwFvg5A53cjuzyhJjD
            4kgddWPIYLrllNW3Jymemnveql+tOYIIMjOP97Vt4LwCFy547tBIsNcRaVI0pBFE
            FpZIhEUo1IjxJ8nCL7ClaLgm+TeRkHhbZMy4LevTbv1uAauIb7HbhkVJC0+pmLQ8
            6pQXNeOt2Arzy8cEPRtuZSFhzqeKkkBx5FDi2s1dfAa+yC4ks61hyf3RQ8/kgPzY
            PcRjP/8CadJKLCm1qylQSUcrYFn3SalOFWzSiNIwmyNH0OyZG9B2UrsxZ0s3+i7S
            XgENlAQ4vf3sNp+rPLCJIT0QCNjnHXI8A+cJlrjXDL90xUgM+PEu55kayciuHHzb
            V50YPoy1nczQ6WZwrYu7lRR+cpk54zf2fiQnjQScWF/UFCJ0zKxasovG14lmsds=
            =884u
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(data|stringData|.*key|.*crt)$
    version: 3.10.2
