apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: linkwarden
        namespace: linkwarden
      chart: linkwarden
      version: '0.3.3'
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: linkwarden-values
