ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - host: z2m.lan
          paths:
            - path: /
              pathType: Prefix
statefulset:
    securityContext:
        privileged: false
        capabilities:
            add: []
zigbee2mqtt:
    homeassistant:
        enabled: true
        discovery_topic: homeassistant
        status_topic: hass/status
        legacy_entity_attributes: true
        legacy_triggers: false
    permit_join: false
    blocklist: []
    availability:
        active:
            # -- Time after which an active device will be marked as offline in
            # minutes (default = 10 minutes)
            timeout: 10
        passive:
            # -- Time after which a passive device will be marked as offline in
            # minutes (default = 1500 minutes aka 25 hours)
            timeout: 1500
    timezone: Europe/Paris
    external_converters: []
    mqtt:
        server: mqtt://localhost:1883
    serial:
        port: tcp://10.1.1.159:6638
        baudrate: 115200
        rtscts: false
        adapter: ember
sops:
    lastmodified: "2026-04-04T22:49:50Z"
    mac: ENC[AES256_GCM,data:E+IbMPEX3CND1R1PlnSgSipopaGwyEM7LubPw5Ead6MlJLS0HOYjSvo0jxyLqJLz/quAsmFhbJBrdNUQFsRoR8BTOXOFr09HXXEZUArm4fpCsif7sk9emInxn1AVzWEohqW2MokeRQO8JN5x8WFyOe1t9ho+foJsz4wDvKABgCk=,iv:rigzrlbd4YpjlSQ7RXk1W1XK29FGADxH80HyJPrx2LY=,tag:wwqylu5PXT8T5QjZW9uOIw==,type:str]
    pgp:
        - created_at: "2026-04-04T22:49:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//Q/aedTUGphu+YwEfOrEI79ZbTof7K97Zk6gC880l9pON
            4GZsGBmigPXMlI12COj1BqHjXFFo766v6x+UtxVBYQZaWICDsN8oTzpxqIuiRr4n
            ismloRYLgK8xDV4TIkqEBZ/BTYhpxGnin4hW29Awh96YsqyGFWDEuq52zgPn6arc
            ibvQFj2VZGbd41qdJ9/9a40PYZD5ARqNXsB8POK+JnX7ETLJyrBZxF9dXSQStbm+
            BeXOAxZgDam9IMX3RiBEr30GWBF6hoaCZ3R6Ukw11jnGMskoLLEPrABE/ZWaQbjD
            Rc1BEohwJTHVKMcKykaWy/uwL74nFEzXPT95pfRsAhcd9hXXSrxu26aYx2oJnYZz
            6ptLwU5X1JW7T5dtvtyciTc4SP4paIlf9Jkxv5TWBMVXYs/85fsU66OJa0IJMA9y
            Mxwzqxcnlr8D13Gh86kYCxno+MnB6EhC1oZSr6tUbfUKirQGjpBccIwwk8RvaCmb
            tElN8jq7MCqA8iom+ZosK0ZPDdzSAqTfTI7cezXsIWViX8U/QJ6shVnIDXpx+6kB
            r9e/Z34m3RJhD/zbQO0T9lJRi+ydNiTwN/SN3i8Z+tIp47fzM+d0CKn7Gv+HwL3d
            YuPbasAtCf9l3YKbHh5y8iRTuae17y0ZjcVvlA0UDT4f8Dub5WlxRpZCCe1utSrS
            XgF6sfnfYbrFwZzdzTT8EcP7LBocqdhsXr2xOm1co26w+94UbfWLMV3iqySsUmcV
            KTk5Z+OCMweMVYkNVxtaL1TsztZORljl8xwb7Th03yzFNZdg2pPzwBur+GknCfo=
            =fH2t
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
