ingress:
    enabled: true
    hosts:
        - host: z2m.lan
          paths:
            - path: /
              pathType: Prefix
statefulset:
    securityContext:
        privileged: false
        capabilities:
            add: []
zigbee2mqtt:
    homeassistant:
        enabled: true
        discovery_topic: homeassistant
        status_topic: hass/status
        legacy_entity_attributes: true
        legacy_triggers: false
    permit_join: false
    blocklist: []
    availability:
        active:
            # -- Time after which an active device will be marked as offline in
            # minutes (default = 10 minutes)
            timeout: 10
        passive:
            # -- Time after which a passive device will be marked as offline in
            # minutes (default = 1500 minutes aka 25 hours)
            timeout: 1500
    timezone: Europe/Paris
    external_converters: []
    mqtt:
        server: mqtt://localhost:1883
    serial:
        port: tcp://10.1.1.159:6638
        baudrate: 115200
        rtscts: false
sops:
    lastmodified: "2026-04-04T22:24:03Z"
    mac: ENC[AES256_GCM,data:h0RYhi23aTXnn9YbeBtuzKD37vazyN4/jALBSmu+6RNl9FnmYo+IUmMGZ7kCr9NRB4w5AQkA7sHO7dBWLq7cEX0LE1B4KIlI6tk4tXYF+CquDYWiMOknqFeIsg14MiRFNbSE07Xjcvpio7ApU6dlGY1WwSegMy6vpEN5dma78RM=,iv:ujPBARrguNPNrbbL+kLM0x9mUvAz2cJn/99UkjGnG4U=,tag:Ee5xv340jVO3FGoqQ7xtBA==,type:str]
    pgp:
        - created_at: "2026-04-04T22:24:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//faG0luLekVqyHsKZLs4NY9xR5vdAfEc8s9Fh816WyTct
            ouFLyk3QqMjkUgeQqr+WIq8EinWoKVh4q3SReSvp7A/9MT28nIFp035KzVNrKFbU
            OiiIdaP4BpSclorLeLfQSsU1vkc/mix4JozxBtjt8N9n+fCJPs4EdLjuSEdwlp8G
            YmHpaxzREURBgZ+MKZQUNTJqFpaICSmPxfgqLuLow9p528j8QgzrIEumWHN4ai+Q
            6mX2KTrJvBQeqqPTh6fRysqm02RMwn3MPMA1No1DzZyeOznuCq19icieQMDZaN7l
            4Mnlf7LLNVHk/VG2r8+nj1glyRhHiG9tSrZckDm4/Vl+f8q1QMfuk+6FgLTe/eUN
            58aM9BRchP35DvwzRiDmtoAqX97w1oCGLyzMhUjWFNUimJeYOtoYPE1b+QTVx+HJ
            GwXlqiaOYxmrYES1d/jn2uxVurwSMkTpSS0Wfb/0P7h0r0RJX4IIoYqBTxmIRWJ5
            ObK+lpjpXvmiX27VoqL2kJTONNxp0LVQEhJhh9gTCOxUC5Azo0mmxJ7BpFJ2SxW5
            eB09wdfQqc9DT00g7FFt82DqJ284kY3Hq7pAJvss7OsKrEB/s6nZgP6exwcl7kOf
            GfHR9lLYTssAQziEiBiRzRtO06kRrkAaFnOUn/CI3kguxEpraj6luyhps/A6TerS
            XgFrrHkNNghYdsSHRyLV7Tjm8ThFVXCjck6T5w6x8J67PC3ihoF+kdUFiT93qM/2
            yWUge1gImo4n7nMTpT17lKpmxJ0C0GrZ4Ceh2Ss5gqeMOrJmoRTa0UjwC4tYamw=
            =7YiG
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
