providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./production
    default_ttl: 3600
    enforce_order: True
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
  porkbun:
    class: octodns_porkbun.PorkbunProvider
    api_key: env/PORKBUN_API_KEY
    secret_key: env/PORKBUN_SECRET_KEY

zones:
  vhaudiquet.fr.:
    sources:
      - config
    targets:
      - cloudflare
  buildpath.win.:
    sources:
      - config
    targets:
      - cloudflare
  saggar.dev.:
    sources:
      - config
    targets:
      - porkbun
