apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      chart: traefik
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: traefik-values
