apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      chart: authentik
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: authentik-values
