services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:2.6.2
    networks:
      - default
      - proxy
    volumes:
      - data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080"
    environment:
      - TZ=Europe/Paris
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.lan`)"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/zigbee2mqtt/data'

networks:
  proxy:
    external: true
    name: proxy
