services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2025.7.1"
    ports:
      - "8123"
    networks:
      - default
      - proxy
    environment:
      - TZ=Europe/Paris
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.local`)"

volumes:
  ha_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/home-assistant/config'

networks:
  proxy:
    external: true
    name: proxy
