# Number of replicas
replicaCount: 1
# Container image configuration
image:
    repository: git.vhaudiquet.fr/semerys/semery.fr
    pullPolicy: IfNotPresent
    # The image tag defaults to the chart appVersion (which is set to git SHA by CI).
    # Override this only if you need a specific version.
    tag: ""
# Image pull secrets for private registries
# (image is anonymously pullable from Gitea, same as vhaudiquet-fr)
imagePullSecrets: []
# Ingress configuration
ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
        - host: semery.fr
          paths:
            - path: /
              pathType: Prefix
    tls: []
# Tolerate failover nodes
tolerations:
    - key: ENC[AES256_GCM,data:AAvY6dhjiqTC,iv:Wppxrm/iJUNjc/TZvC9mPDAa3toF5BhkLUkuqh77bIg=,tag:p9QKeRskh/y26zjI36freA==,type:str]
      operator: Equal
      value: ENC[AES256_GCM,data:m5zWONDhDNw=,iv:ylrQNif/KiQvcyXqIvkCQCiqKaacNElHC90rCGmG9kk=,tag:h+Xm0I9UeEJ33UEq7g1URg==,type:str]
      effect: NoSchedule
    - key: ENC[AES256_GCM,data:FdFM3MInrxMTdioB96eLjf1SuZZFNQOxV3/qjFer8wX/cG43OA==,iv:bTi0PaS0gn/FsxyIIjPpq2rN+tnotqZoiGuZyMSOP68=,tag:5V8LogK4UVMsCUS1fgrwDw==,type:str]
      operator: Exists
      effect: NoSchedule
# Prefer (non-failover nodes) in normal operation
affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                    - key: ENC[AES256_GCM,data:jgNJn7jRN+dMELJ63ywucpnXmOw=,iv:M2uNhIywAnHs4IFCfXNyI5HV3Hb5sCjP7pz3/Yl/nTY=,tag:FS+VvTZmzmQILjvJW8Ceiw==,type:str]
                      operator: NotIn
                      values:
                        - "true"
sops:
    lastmodified: "2026-08-26T19:28:04Z"
    mac: ENC[AES256_GCM,data:0krPSq8UdOyscNONBsWoRXA6qfDrBlDmm7wa4RMRGnkeI0lM3+GM2PiUtlinrqL6MAvIHlzKTkgG/SuWQoD+Uj2aM6PSxHsIfnxoW/chqVLrw+Q2GvIMlehEKNEsDM/dedvZhIryA6Pl7qD/4xKrkQjlj8LEyrq0qC3OqnHk2Uk=,iv:tQvpZPQUFKdFxcv5ucMSGrzFMJDC5TLP2RsYjYOtaK0=,tag:397SQXa1AYTEzI0gaa2JKA==,type:str]
    pgp:
        - created_at: "2026-08-26T19:28:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//fmb1BXRMO8INJV9P2ru3R1wDKNO/YCW/ohYhGeRlcNvS
            y1vIY+GZ5ClPaWMgqcVAUbDmOKseOOXSPhaDPkVwECDsX2nzKSIKAIX9AihD07pl
            wnDKY840Iogosf8yVHkJmiTCTCcXmj3yoynGDuwiPbi4+pA92ebCx6igCGdUFaTD
            nbUhDhEVIfMNq5sqmt4ppYuAk3XHabw/g2aF8Tse+thqLlZOeDNmhFVq+sboR6GC
            KNa6Zxqo2Pp3OjvAjqOVIE9pVNY61DEErj/LzsBGDzo6Sg4qckv8h41lPxbm+Gq3
            pm7/ytJ1F1ZEk2dfiMgFvMZ6yKi+urWAklZWdsw7II91kvqZ1HZv2JEWC+61Sh5O
            KngWeZ2wP+Uu6bnBpWzpOpvyKqNb9NcDniwpdE/2KNpVMuWZ5x+G+eLhIS2R+9Nm
            AiwGpUTsXZv6aT1oeRHDuW7T9EurZYqfNSuJqSZaDJZhYS+PdwUF25eqxb8Vpxo/
            pNI0zLOtn7C2kXVgUSQLyD/mGcpNo53Vr7K0myg8RYkuR8l7ucbiczf/4YQguDJS
            Ntxhi8ChVTAtcerpuCtMwYRVlatISf/4jnx1XJi0Im0kQoTPDN/ybqt5wTK/DtHG
            gwgJsPO8uLfCmNjtKw2c282e1jlDJGTFgKfH6ls3jBY08Uql8qTjgsFa+fL+eanS
            XAHUEmqmezCImPSyF7Lu18rlB26o3W16FmglTuy7jwV5NsuZJBJVegu5x+oz7xOa
            2eE4xIpk6Iq3q1AAvbyiLNsvli5tm8mTFjMAZ275DLWps2QlFLFYPmi0nZ9k
            =K7AY
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*PASS|.*SOCIALACCOUNT_PROVIDERS|.*\.ya?ml)$
    mac_only_encrypted: true
    version: 3.10.2
