apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: observability
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/grafana-community/helm-charts