apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      chart: external-dns
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: external-dns-values
