provider:
    name: coredns
    registry: noop
    policy: upsert-only
    sources:
        - ingress
domainFilters:
    - .lan
extraArgs:
    - ENC[AES256_GCM,data:u6qw40tfgn73KEP/m32c/gCOPx+/9acgvJU=,iv:A2g5Af2YC7OYkSnEadAmKaSzvrB/aPiDtjWCxWGL51U=,tag:Fd25mqGJtwCK7eUNMr7sCQ==,type:str]
    - ENC[AES256_GCM,data:nd31hq1/EPerMXB1I0QSmHCr,iv:/hCDwU24JNqYKZIFfSSerxvYVsdiFr7h6+YQxY4yVQk=,tag:EOmmGns8E9z9KECsVZjUdg==,type:str]
env:
    - name: ETCD_URLS
      value: ENC[AES256_GCM,data:c1aXvAvXWSe7oEKxXpEPOeBuacbccc6Yj6hX1qZh/qbyHahJDG/hFmN2YXEe,iv:n0PsS9AughHZLlKQ9sPBwJvmoROFZV/APPCWGJgPARs=,tag:FR4U0igmBQ7bMbXSYd3Vkw==,type:str]
sops:
    lastmodified: "2026-05-02T13:58:23Z"
    mac: ENC[AES256_GCM,data:rH8SvC0kOL1E+cHrRaFgLKtjlVgqyI3MbMVMtt73sOmYnyE3MqJTvRAOSzRNeZU+5VBQ/NrHVUyP5hzd0gN1v/lqNIDNzo3MmcvcHZG9g3Hvo1LmsVyY9JdNx5RNJFMokFzr9bKmeSiia5wtpoM4L1wA+VE7CDt9Dx745pzm87I=,iv:Y/oSE9xQjJznBFUrXnRWZ8X1GOYR7OuOOd2A14S7m9g=,tag:L/MiiAtvYBHw91wJZw8yyQ==,type:str]
    pgp:
        - created_at: "2026-05-02T13:58:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiARAAqzzr5TVwekK1oPMnlpeVJxs5BuVxSPa7qAarZCidXPEa
            CE/tAHNtnat7grvHjIjijuZsYSDwP2eBZaQotIPmoRnu06SfD3Dc9/jSCPqefa5c
            J/xRbJdqx8lyMQkXFVr9AvPCkrR+pypDUvA+BxXbCkfMoy3xmbqmG51ql0U/joEd
            Z6cFY5Xd+4a5E2sJDicrtQHTy0KF1b66EthMf0jFaRfX4gAaHQuxLDDnEr1+c/JA
            udQokySmmQzIIDcFxPE8071buBDAXj35ePOTh5vAPLPt7CcRjmEEPhC8xA5ksimN
            uZmafCGMIXFg1Vzxg6r7vzxCJokWr+cWMP+ocWcpjEBGm9+uP7JFneb/AZ1W/W95
            oblnkoH0NfJELN6b0qc3CTm5VAM3I8ysdoUcjOTc/cVAgp0cP2UcK86PMCLieBx7
            /hOKPM+QPn17kcWMe2+0aDvAormUkdwIpM2bRItkwDUM1AKTpTk1NKvs6EIIQZmL
            V+4lmLkjD+C2YrGjz4f0oFDH9zTOxzAdhh0MxT4xtdQjbckzGcC2jl+VC/rQZZj6
            yCtyd1EfcmivvbD8iBRLRozLggS1qODB6CwWiFIVNPpY6FYGGWneNTpkYhKrPiGb
            6zoI0K0Sbr7bZEtn9dZ3JBzABlj2+9NZmP1EAkQLsqCBOBvdEIa3gNxM0VT28ffS
            XgHZcKe8kQlniJRrdQZGSaK7Cv6/Ibo678yZIzNebxWDTlFCgUNyaK4Wh3wF+3Lx
            wodYqILIoLIZ32eRabgeCQKk+/9kWnwf6stq+2X40mECY95ZTLJilxK8qtaxMzc=
            =Phmg
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
