provider:
    name: coredns
    registry: noop
    policy: upsert-only
    sources:
        - ingress
        - service
domainFilters:
    - lan
extraArgs:
    - ENC[AES256_GCM,data:ROsCDtsBUq2t9Sl5Y0WNl3O2s874XO5ufQY=,iv:9xi23C17iD6SjfPal6QPEB92whanuRcvxmumXViu5us=,tag:1cNiSR+FIfyUc208EU+ARw==,type:str]
env:
    - name: ETCD_URLS
      value: ENC[AES256_GCM,data:zSVnR60AwLy4ureIuQPpyT9RwbXKOhNsCqgKS6DkY2PraDZRZ8hK2jG+,iv:H+U40tb4vF5U+8Xc+QYTYK94PxKVvQo/ydieQOAE4rY=,tag:HxpMn4ShQV+ldQ9nq9mdXQ==,type:str]
sops:
    lastmodified: "2026-05-02T14:03:48Z"
    mac: ENC[AES256_GCM,data:36FJ1MKWtsMHtag58sAvt5FGQ5NQcJIo+b3fgooZ+PVxz9UDBd9EW73SWa3UMHxm+9Ll1VZUWb1akUlRYmCi8Iy+rVjzRJevyptFuQAqqQR/fRiqxdKR/WeqvJFysVfryL59vQ7jhExIL+GFnTYd4CSDB5WqufD5BKBiCQWUHfY=,iv:m8yPLDyvK5eP4jUTmrBXvKjdZlfcz57/TrPHVDce/sA=,tag:RFCZUfgWfXEZNk8t5G7b9Q==,type:str]
    pgp:
        - created_at: "2026-05-02T14:03:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7uy4qQr71wiAQ//aBT/sFQBvwFYuu352558P2MI5Vzu/+DNhWgCXo5sjMFa
            9W6HgsIlYHq1FvcfqaEyuEJGnAvc+qvhTd7TNLlIxqcLgx4hgmpAeFVUDmkfZ7Na
            ZF+iOkinPERscuwqYD4Yh9WoH2oSDtlRMSslZR/I9Y20IVhH4nS5pAgvjsI0UvWt
            N253/UMV8e/vkY9QSmYf3oyYeeHQQ7iOM1ySfSozlG+VspOTlw3ILel62RUCRgFM
            iPlKlwYbLPwMrEpGZ5lETtr32PU2Ba6yHSVo+dWX4hyk5VkL6a6hLXXJKrT4Qm3y
            512fChIfRItEYuu4gnNVcY8TTfWr6kcYhK8FWmgSKF0aMp1LKp9iJibFd1Cvxcs4
            82g61irbfq1f2KKruX1+hqzBvy+3mDuL/gCBe3GCtKZmDkWymS7f4hB+TZ2Hu4sA
            dHHT75/uC07yyXbB8nRqNEGp9VpOW2Y65vEXePpGSXheVYvWDp/du8zwmuvz/j+k
            4JP14Low2RuCkDmoMCbE89KMePFzsiVIhKulYfSB/4Xcg505JldPDAsBG0+dFJgb
            h0f1tWS/jfov+NSvX0AqvJka4hDzm8I1akn5FlHHXQTuTamASLtgYaGJuUB7oLV/
            UimdoWlL3rK7hZ3QKxD/DRV4u1PKU4Ky5nz6VN0dChNBU21/VQFtDU88oUUYoTjS
            XAG9N45iomxXGC8T51Uz13WSN6+sxW34nrRyxUsJz/IJObhWAvFSatLT069mQo/T
            0XA8t2lcchkRDfwot2mcq53y/s/LQ/DPeJRMR6s6pUigQtzo8OSX5Sj6Nrnx
            =HfJ1
            -----END PGP MESSAGE-----
          fp: DC6910268E657FF70BA7EC289974494E76938DDC
    encrypted_regex: ^(password|value|ssh-key|api-key|user|username|privateKey|clientSecret|clientId|apiKey|extraArgs.*|.*Secret.*|extraEnvVars|.*SECRET.*|.*secret.*|key|.*Password|.*\.ya?ml)$
    version: 3.10.2
